### ISSUE TITLE
config.php not being created

### ISSUE THREAD

**Issue by TheSpartaPT** [ToxicRevolution/CSGORankMeWeb#10]
so i can't access the page whenever the config.php file isn't there (it doesn't automatically create it after i complete the install script), and if i create the file myself i can access the page but it won't work because it didn't save all the settings i put on the install script to the config.php nor did it create it :/ help ? my php version is 5.6.30 thanks :)

**Comment by APet74** [comment]
Kenny or myself will look into this. Check any error logs to make sure that file writing is allowed  may need to check script permissions. If nothing else Kenny or myself can provide you a working config.php

**Comment by TheSpartaPT** [comment]
i also have sourcebans++ on the same machine, the install process seems similar idk what is hapening with this one :/ can you give me a list of the files that i need to check the write permissions ? is it only the install.php ? because it has chmod 644 like all the stuff i already checked

**Comment by TheSpartaPT** [comment]
the folder that contains all the files has chmod 755

**Comment by TheSpartaPT** [comment]
also thanks for the fast answers really appreciating it :)

**Comment by kennyLtv** [comment]
anything in the error logs about it?

**Comment by TheSpartaPT** [comment]
do i just copy and paste it here or do you prefer pastebin ?

**Comment by kennyLtv** [comment]
I believe you can insert code here

**Comment by TheSpartaPT** [comment]
`[Wed May 17 18:57:14.969288 2017] [:error] [pid 22109] [client 172.68.102.81:17075] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 18:57:14.969386 2017] [:error] [pid 22109] [client 172.68.102.81:17075] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:10.554406 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fopen(../config.php): failed to open stream: Permission denied in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 8, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554465 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Notice:  Undefined index: serverType in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 28, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554477 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 33, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554481 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 34, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554485 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 35, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554489 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 36, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554492 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 37, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554496 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 38, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554501 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 41, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554505 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 45, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554509 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 47, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:10.554518 2017] [:error] [pid 22049] [client 172.68.102.81:36339] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 49, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:00:29.574454 2017] [:error] [pid 22050] [client 172.68.102.81:17354] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:29.574501 2017] [:error] [pid 22050] [client 172.68.102.81:17354] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:32.270060 2017] [:error] [pid 22034] [client 172.68.102.81:10117] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:32.270099 2017] [:error] [pid 22034] [client 172.68.102.81:10117] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:32.979406 2017] [:error] [pid 22033] [client 172.68.102.81:23514] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:32.979448 2017] [:error] [pid 22033] [client 172.68.102.81:23514] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:33.606254 2017] [:error] [pid 22110] [client 172.68.102.81:19945] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:33.606301 2017] [:error] [pid 22110] [client 172.68.102.81:19945] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:34.682391 2017] [:error] [pid 22035] [client 172.68.102.81:34829] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:34.682435 2017] [:error] [pid 22035] [client 172.68.102.81:34829] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:35.282795 2017] [:error] [pid 22117] [client 172.68.102.81:11586] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:35.282844 2017] [:error] [pid 22117] [client 172.68.102.81:11586] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:53.280795 2017] [:error] [pid 22111] [client 172.68.102.81:34369] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:00:53.280838 2017] [:error] [pid 22111] [client 172.68.102.81:34369] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:01:09.903320 2017] [:error] [pid 22050] [client 172.68.102.81:20664] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/authenticate.php on line 3, referer: http://thesparta.tk/rankme3/login.php
[Wed May 17 19:01:09.903355 2017] [:error] [pid 22050] [client 172.68.102.81:20664] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/authenticate.php on line 3, referer: http://thesparta.tk/rankme3/login.php
[Wed May 17 19:03:26.245507 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fopen(../config.php): failed to open stream: Permission denied in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 8, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245655 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Notice:  Undefined index: serverType in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 28, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245701 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 33, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245707 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 34, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245711 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 35, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245714 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 36, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245718 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 37, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245721 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 38, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245729 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 41, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245736 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 45, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245741 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 47, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:26.245758 2017] [:error] [pid 22117] [client 172.68.102.81:30834] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 49, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:03:32.932975 2017] [:error] [pid 22111] [client 172.68.102.81:13651] PHP Warning:  require_once(config.php): failed to open stream: No such file or directory in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:03:32.933055 2017] [:error] [pid 22111] [client 172.68.102.81:13651] PHP Fatal error:  require_once(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/thesparta.tk/rankme3/index.php on line 6
[Wed May 17 19:03:50.420003 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fopen(../config.php): failed to open stream: Permission denied in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 8
[Wed May 17 19:03:50.420041 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: pageTitle in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 16
[Wed May 17 19:03:50.420048 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: check in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 17
[Wed May 17 19:03:50.420055 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  Invalid argument supplied for foreach() in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 18
[Wed May 17 19:03:50.420108 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: browserTitle in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 27
[Wed May 17 19:03:50.420145 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: serverType in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 28
[Wed May 17 19:03:50.420150 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: databaseIP in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 31
[Wed May 17 19:03:50.420181 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: databaseName in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 31
[Wed May 17 19:03:50.420185 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: databaseUser in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 31
[Wed May 17 19:03:50.420189 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: databasePass in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 31
[Wed May 17 19:03:50.420196 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 33
[Wed May 17 19:03:50.420199 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 34
[Wed May 17 19:03:50.420203 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 35
[Wed May 17 19:03:50.420206 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 36
[Wed May 17 19:03:50.420209 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 37
[Wed May 17 19:03:50.420212 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 38
[Wed May 17 19:03:50.420261 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 47
[Wed May 17 19:03:50.420276 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 49
[Wed May 17 19:03:50.420340 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: databaseIP in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 51
[Wed May 17 19:03:50.420347 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: databaseName in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 51
[Wed May 17 19:03:50.420351 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: databaseUser in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 51
[Wed May 17 19:03:50.420355 2017] [:error] [pid 22118] [client 172.68.102.81:33887] PHP Notice:  Undefined index: databasePass in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 51
[Wed May 17 19:08:09.843137 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fopen(../config.php): failed to open stream: Permission denied in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 8, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843261 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Notice:  Undefined index: serverType in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 28, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843306 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 33, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843315 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 34, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843320 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 35, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843325 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 36, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843330 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 37, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843335 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 38, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843342 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 41, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843349 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 45, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843354 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 47, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:09.843361 2017] [:error] [pid 22039] [client 172.68.102.81:18987] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 49, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373442 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fopen(../config.php): failed to open stream: Permission denied in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 8, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373526 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Notice:  Undefined index: serverType in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 28, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373543 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 33, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373548 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 34, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373568 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 35, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373572 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 36, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373575 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 37, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373578 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 38, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373583 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 41, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373587 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 45, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373591 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 47, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:08:56.373599 2017] [:error] [pid 22118] [client 172.68.102.81:35608] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 49, referer: http://thesparta.tk/rankme3/install/install.php
[Wed May 17 19:12:20.581003 2017] [:error] [pid 22039] [client 172.68.102.81:24172] PHP Notice:  Undefined variable: webTitle in /var/www/thesparta.tk/rankme3/index.php on line 10
[Wed May 17 19:12:20.581781 2017] [:error] [pid 22039] [client 172.68.102.81:24172] PHP Notice:  Undefined variable: pageTitle in /var/www/thesparta.tk/rankme3/views/nav/index.php on line 4
[Wed May 17 19:12:20.581978 2017] [:error] [pid 22039] [client 172.68.102.81:24172] PHP Notice:  Undefined variable: pageTitle in /var/www/thesparta.tk/rankme3/views/home/index.php on line 6
[Wed May 17 19:12:20.582010 2017] [:error] [pid 22039] [client 172.68.102.81:24172] PHP Fatal error:  Call to undefined function getTotalPlayers() in /var/www/thesparta.tk/rankme3/views/home/index.php on line 44
[Wed May 17 19:12:38.776826 2017] [:error] [pid 22049] [client 172.68.102.81:18328] PHP Notice:  Undefined variable: webTitle in /var/www/thesparta.tk/rankme3/leaderboards.php on line 10, referer: http://thesparta.tk/rankme3/
[Wed May 17 19:12:38.776903 2017] [:error] [pid 22049] [client 172.68.102.81:18328] PHP Notice:  Undefined variable: pageTitle in /var/www/thesparta.tk/rankme3/views/nav/index.php on line 4, referer: http://thesparta.tk/rankme3/
[Wed May 17 19:12:39.521838 2017] [:error] [pid 22117] [client 172.68.102.81:9172] PHP Fatal error:  Call to undefined function getLeaderBoardInfo() in /var/www/thesparta.tk/rankme3/control/leaderboard/leaderboardGrab.php on line 7, referer: http://thesparta.tk/rankme3/leaderboards.php
[Wed May 17 19:12:57.927220 2017] [:error] [pid 22039] [client 172.68.102.81:14571] PHP Notice:  Undefined variable: dbh in /var/www/thesparta.tk/rankme3/authenticate.php on line 5, referer: http://thesparta.tk/rankme3/login.php
[Wed May 17 19:12:57.927276 2017] [:error] [pid 22039] [client 172.68.102.81:14571] PHP Fatal error:  Call to a member function prepare() on null in /var/www/thesparta.tk/rankme3/authenticate.php on line 5, referer: http://thesparta.tk/rankme3/login.php`

**Comment by TheSpartaPT** [comment]
that is everything that has to do with your script

**Comment by APet74** [comment]
Permission denied for fopen, that's what I am seeing, rest of the warnings for fwrite are because it couldn't open. Kenny can you help him. If not I will at the hotel.

**Comment by kennyLtv** [comment]
`PHP Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/thesparta.tk/rankme3/install/installMethods.php on line 33, referer: http://thesparta.tk/rankme3/install/install.php`

Similar issue here: https://github.com/ToxicRevolution/CSGORankMeWeb/issues/9

They ended up not having the correct top level directory permisions. Please be sure the ownsership and permissions of the top level is correct

**Comment by TheSpartaPT** [comment]
my top level permissions are 755 idk if that's what it is supposed to be but i already said that :/

**Comment by kennyLtv** [comment]
right the permissions are 755 but is the ownership of it correct?

**Comment by kennyLtv** [comment]
if it is here is an example of the config. you can try making it manually https://gist.github.com/kennyLtv/2fbe068bbbf0ad2d719ba323c777ecbc

**Comment by TheSpartaPT** [comment]
owner id: 0
group id: 0
account that i'm using root id: 0 ... :/

**Comment by TheSpartaPT** [comment]
ok thanks let me try that

**Comment by TheSpartaPT** [comment]
it works, thanks :) kinda of a random error tbh, you should just add the config.php to the repo just in case somebody else needs it

**Comment by kennyLtv** [comment]
Would you be so kind as to go into /var/www/thesparta.tk/ and send me a screen shot of the permissions for rankme3? so I can see ownership and perms. Also do you mind telling me your OS and your web server?

**Comment by TheSpartaPT** [comment]
webserver: Apache2
OS: Debian 7
![rankme3](https://cloud.githubusercontent.com/assets/8343238/26169736/aecb0b3e-3b36-11e7-9189-2a30c314ba21.png)

**Comment by kennyLtv** [comment]
Do you have ssh access to the server? If so can you show the ownership from ssh?

**Comment by TheSpartaPT** [comment]
yes i do, that is bitvise, an ssh / sftp client it will show you basically the same thing but on the console because it connects me to ssh and sftp both at the same time and with the same account

**Comment by kennyLtv** [comment]
its just weird usually user and group is something like www-data in the case of apache. So I was just wondering what it said in ssh

**Comment by TheSpartaPT** [comment]
let me have a look then

**Comment by TheSpartaPT** [comment]
sorry for the delay, something else hapened meanwhile, here's what you want i think :/
![rankme3_console](https://cloud.githubusercontent.com/assets/8343238/26170669/246ed17e-3b3a-11e7-8a58-c83d58b36cf0.png)

**Comment by kennyLtv** [comment]
I believe that Debian Apache runs as user www-data and group www-data so that may be why fwrite() and fopen() didn't have the required permission to create the config

**Comment by TheSpartaPT** [comment]
that would probably be it, but installing sourcebans++ worked just fine and the process is similar: sourcebans.thesparta.tk ... so idk anymore

**Comment by kennyLtv** [comment]
is the owner and group for the sourcebans ++ install the same as rank me?

**Comment by TheSpartaPT** [comment]
yes

**Comment by kennyLtv** [comment]
hmmm ok, thats weird. Wonder if they use fopen() and fwrite() gunna go find out

**Comment by kennyLtv** [comment]
`if (!file_exists("../config.php") && is_writable('../')) {
    $handle = fopen("../config.php", "w");
    fclose($handle);
}`
can confirm they use fopen()
