### ISSUE TITLE
Developed 

### ISSUE THREAD

**Issue by spot88** [ToxicRevolution/CSGORankMeWeb#22]
Is this still beeing developed?

**Comment by kennyLtv** [comment]
I would say currently that CSGORankMeWeb is being maintained, both Andy and I are busy with school or other projects. We do our best to address problems and concerns and have some ideas sitting on the back burner for the project.

**Comment by APet74** [comment]
If you have ideas for what you think should be added please let me know. I like to have projects to work on during my free time. Currently, we don't really have many changes except for basic design changes and the problem with those changes is that we don't know what people would like to see. We need input, if you have ideas, let us know!

**Comment by spot88** [comment]
Awesome, sounds good. Gonna start use it now. i'll come with feedback l8r
