### ISSUE TITLE
<Request> Change default number of entries to show

### ISSUE THREAD

**Issue by spacecow123** [ToxicRevolution/CSGORankMeWeb#26]
Make an option to increase default number of entries to show. Currently it shows only 10 entries on first load.

**Comment by APet74** [comment]
Assuming you are talking about leaderboard? Newest version shows 25 I believe, to change please edit the following values: `"pageLength": 10,` in `js/leaderboard/leaderboardFunctions.js`.  Page length will be the amount shown per page by default.

**Comment by spacecow123** [comment]
Ah, OK so I did a fresh install and now I can change the default # of entries to show. Now I have a new problem, I don't know how to customize the stats columns in the new update. Right now it shows Steam/Score/K/D/ADR/Profile. I would like it to show Score/K/D/Kills/Deaths/Assists/ADR/Profile/RoundsT/RoundsCT.

I knew how to do that myself in the old version but the new version is confusing me, sorry I'm a newbie.

Thanks!

**Comment by APet74** [comment]
I will need to write you some custom pages, I will send you the code when I have a little time. I will get it done as soon as I can.

**Comment by APet74** [comment]
Ok, in your project please replace the following two files with the code found in the pastebins. 

In `control/leaderboard/leaderBoardGrab.php` paste this code: https://pastebin.com/dRCnqGWt
In `views/leaderboards/index.php` paste this code: https://pastebin.com/p9yZssA2

Let me know if that works, it is working for my test data: http://petrzilkacoding.com/RankMeLarge/leaderboards.php

**Comment by spacecow123** [comment]
Works now, http://spacecowcs.xyz/leaderboards.php if you want to see. I figured out how to customize it myself.
