### ISSUE TITLE
php 7.0 breaks webui?

### ISSUE THREAD

**Issue by spacecow123** [ToxicRevolution/CSGORankMeWeb#35]
I had to change my hosting back to php 5.6 and then the webui started working again.

**Comment by kennyLtv** [comment]
Not sure, did it give you errors when it was broken? Going to install it now on 7.0 to see if I can reproduce it.

**Comment by APet74** [comment]
Kenny I am running 7.0 on the test one we use.

**Comment by kennyLtv** [comment]
well, then I guess I don't need to install one...

**Comment by kennyLtv** [comment]
Do you have anything further?

**Comment by spacecow123** [comment]
nope, must be something with my hosting company then. Thanks!
