### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ThanhByKyTa** [ToxicRevolution/CSGORankMeWeb#36]
DataTables warning: table id=LeaderBoardTable - An SQL error occurred: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

https://imgur.com/a/RBfNE

**Comment by APet74** [comment]
Did you use the correct table name in the installer? What's your config look like? Don't forget to blur out your password if you send it to us.

**Comment by ThanhByKyTa** [comment]
My not Database Password 
How i can skip this ?

**Comment by kennyLtv** [comment]
Your using MySQL not SQLite correct?

**Comment by ThanhByKyTa** [comment]
yes and i use xampp

2018-02-23 10:19 GMT+07:00 Kenny Lindelof <notifications@github.com>:

**Comment by kennyLtv** [comment]
Can you send your config file with your password blurred out?

**Comment by APet74** [comment]
It's called config.php, just send it via pastebin.com

**Comment by ThanhByKyTa** [comment]
https://pastebin.com/7njTMhHm

**Comment by kennyLtv** [comment]
Did you run the installer?

**Comment by ThanhByKyTa** [comment]
yes ! 
but my sql not password i can't skip database pass

**Comment by ThanhByKyTa** [comment]
Notice: Undefined index: serverType in C:\xampp\htdocs\rankme\install\installMethods.php on line 28
SQLSTATE[HY000] [1130] Host 'WIN-9MHBB4QL7CM' is not allowed to connect to this MariaDB server
![image](https://user-images.githubusercontent.com/33537916/36603446-59ded8ea-18ed-11e8-9e58-f2016217de2d.png)

**Comment by kennyLtv** [comment]
Ok, I understand now that your database doesn't have a password. That is what I was not understanding. Can you try taking our example config from [here](https://github.com/ToxicRevolution/CSGORankMeWeb/blob/master/example.config.php) and manually filling the database and site info?

**Comment by ThanhByKyTa** [comment]
![image](https://user-images.githubusercontent.com/33537916/36630559-09089768-199b-11e8-83f8-a5e0ef2af5c5.png)

**Comment by kennyLtv** [comment]
So it is working now?

**Comment by ThanhByKyTa** [comment]
yes
