### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by uniquegamingoficial** [ToxicRevolution/CSGORankMeWeb#37]
Hello, after installed the webpage, I acess do /floder/index.php and it says that page is not working...
What's happening? 
I already deleted install folder

**Comment by kennyLtv** [comment]
I need more information. 

Does it give you an error in your error log? 
Are the directory permissions correct?

**Comment by kennyLtv** [comment]
I'm going to close this issue as we have heard nothing further. Please open another issue if you are still having issues.
