### ISSUE TITLE
Problems encountered during installation

### ISSUE THREAD

**Issue by nishuo** [ToxicRevolution/CSGORankMeWeb#38]
Is there a requirement for the php version? Or what php extensions need to be turned on? I get an HTTP 500 error when accessing the domain after uploading a folder, php version 7.0.15

**Comment by APet74** [comment]
Is there an Error_log file made, I assume there is some broken syntax when going from your old version to your new version. I can probably fix it if there is some sort of error_log.

**Comment by nishuo** [comment]
I opened the php error message display, please check
[Website](https://rank.hvh.cloud)

**Comment by APet74** [comment]
Is there an error_log in the folder that you can send us?

**Comment by kennyLtv** [comment]
I'm guessing from the error I see on the page you did not use the installer? I have updated our [example config](https://github.com/ToxicRevolution/CSGORankMeWeb/blob/master/example.config.php) to include the missing variables.  Please run the installer or take a look at the example config for variables you may be missing.

**Comment by APet74** [comment]
Yeah, I would agree you are missing a $table variable ism y guess.

**Comment by nishuo** [comment]
Do you use telegram? This may enable us to communicate quickly.

**Comment by kennyLtv** [comment]
We don't use telegram, we have a keybase group you can join [here](https://keybase.io/team/toxicrevolution.development).

**Comment by nishuo** [comment]
▶ cat config.php 
<?php
require_once("control/queryFunctions.php");
require_once("control/class.Player.php");
require_once("control/class.Server.php");
$pageTitle = '';
$weaponsArray = array("m4a1_silencer","m4a1","ak47","awp","knife","usp_silencer","hkp2000","elite","p250","fiveseven","cz75a","deagle","glock","tec9","famas","aug","galilar","sg556","hegrenade","flashbang","smokegrenade","inferno");
$webTitle = '';
$dbh = new PDO("mysql:host=localhost ;dbname=csgo", 'csgo', 'csgocs');
$webURL = ' ';
$sbURL = ' ';
$title = "rankme";
?>

root@Trii:wwwroot/rank.hvh.cloud/CSGORankMeWeb  master ✗

**Comment by APet74** [comment]
needs a $table variable. The $table variable should be the name of the table, usually "rankMe"

**Comment by nishuo** [comment]
Thank you. I will try it later. Now I need to sleep.
