### ISSUE TITLE
[ SUGGESTION ] Put more player rating options

### ISSUE THREAD

**Issue by paulocrash** [ToxicRevolution/CSGORankMeWeb#39]
Could put option of classification by K/D and ADR.

Currently only have by Nick, Steam and Points.

**Comment by kennyLtv** [comment]
It isn't in the scope for the current version of RankMeWeb. I have though tagged this for the rewrite. We can't do it in this version of RankMeWeb due to the way we went about digesting the data.

**Comment by paulocrash** [comment]
I understand, in any case I wait for the new version of RankME Web.

Thank you!
