### ISSUE TITLE
Table doesn't exist

### ISSUE THREAD

**Issue by florinhangu** [ToxicRevolution/CSGORankMeWeb#40]
Hello.
A table is missing. Did not installed. And i re-installed the software 3 times... I cant access leaderboards :(

`DataTables warning: table id=LeaderBoardTable - An SQL error occurred: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rankme.rankme' doesn't exist`

**Comment by APet74** [comment]
Hi Florinhangu, we do not create any tables, the error is probably the name of your table is incorrect. It is not asking you what to name the table but rather asking you to link to the table that has all your rankme data. I can't tell you exactly what it is called because I can't see your database structure.

**Comment by florinhangu** [comment]
Well, there was no table in my mysql database before installation of csgo rank web, and now there are 2 but is missing one :( for leaderboards... the others infos works, like server, admin, users.
![db](https://user-images.githubusercontent.com/14860565/41430141-e48f593e-7017-11e8-9d21-7f370580ed24.png)

**Comment by florinhangu** [comment]
![srv](https://user-images.githubusercontent.com/14860565/41430203-0c4e70fe-7018-11e8-9287-ae08b551dc6e.png)

**Comment by APet74** [comment]
Do you have the plugin running on your servers yet?

**Comment by florinhangu** [comment]
Haha... actually, the cs:go plugin create the tables, but your softwares read it... i appologize, it fixed after restart!

**Comment by APet74** [comment]
Yeah, that is what I figured the problem was! Anyways, if it does give you any hassle let us know! 💃
