### ISSUE TITLE
Stop JS from Leaderboards

### ISSUE THREAD

**Issue by florinhangu** [ToxicRevolution/CSGORankMeWeb#41]
Hello.

How can i stop the JS from leaderboard web page. I want my page to be static. I do not want to shrink.

**Comment by APet74** [comment]
What do you mean Shrink?

**Comment by florinhangu** [comment]
I dont want to have the left to right  movement...

![move](https://user-images.githubusercontent.com/14860565/41433785-9b3d9600-7022-11e8-827e-5dd5e5c79750.png)

**Comment by APet74** [comment]
I don't see the left to right scroll bar?

**Comment by florinhangu** [comment]
That because the leaderboard starts in left and shrink to left until becomes regular.

![20180614_223555](https://user-images.githubusercontent.com/14860565/41434163-821c3f18-7023-11e8-9658-75aec6346959.gif)

**Comment by APet74** [comment]
The shrinking is the responsiveness from the DataTables plugin. You just want it to start small and not shrink?

**Comment by nguyenbaodanh** [comment]
Can make the theme to mobile compatible ?

**Comment by APet74** [comment]
Currently, it uses Bootstrap so it is "responsive" however we did not make it compatible for mobile. We are working on releasing a couple new versions of the web plugin soon so we may work towards making one mobile responsive as well.

**Comment by florinhangu** [comment]
> The shrinking is the responsiveness from the DataTables plugin. You just want it to start small and not shrink?

Yes please!

**Comment by kennyLtv** [comment]
Honestly not sure why that animation is happening. We are working on a new release based on Laravel and ReactJS. The release will include mobile responsiveness for most if not all aspects of the web panel. Until that release, it may just be something that you have to deal with as we are not sure what is causing it.
