### ISSUE TITLE
Leaderboard Generation Errors

### ISSUE THREAD

**Issue by TandelK** [ToxicRevolution/CSGORankMeWeb#43]
Whenever some try to open leaderboard they get the following error message 

`DataTables warning: table id=LeaderBoardTable - An error occurred while connecting to the database. The error reported by the server was: SQLSTATE[HY000] [2002] No route to host
`
I tried accessing the SQL from other application with Same Username and Password and all are working fine but only error is coming is on LeaderBoard Page. Even i can make a custom search using Steam ID on Player Search option with Steam ID.

**Comment by APet74** [comment]
Database and web server hosted at the same place? Does the database host allow the remote connection?

**Comment by TandelK** [comment]
nope they are at different locations and on the same web host i have different database with the same username and password and that is working fine .

**Comment by kennyLtv** [comment]
If I understood that correctly you can connect to the local database but not the remote database? In which case your MySQL user is either not allowing remote access or your Firewall is not allowing the connection.

**Comment by TandelK** [comment]
Closed it , i change the host of my panel and now its working fine for some reason it might have added old Panel IP In blacklist or limitations
