### ISSUE TITLE
Weird Database Issue

### ISSUE THREAD

**Issue by punkstarharis** [ToxicRevolution/CSGORankMeWeb#46]
im having this issue (attaching screenshot) already made database with the name of Ranking but idk why this happening 
![capture](https://user-images.githubusercontent.com/28386395/41807409-331695c8-76e8-11e8-9a42-5e29f646eec2.PNG)

**Comment by punkstarharis** [comment]
just made a database with the name of ranking from database wizard there is no table option in database wizard

**Comment by punkstarharis** [comment]
server is also crashing with this error
![capture](https://user-images.githubusercontent.com/28386395/41807542-8bc252e2-76e9-11e8-8b07-90ff17c1035a.PNG)

**Comment by TandelK** [comment]
What version of RankMe are you using ? Kento or the Old CSGO Version which was mainly developed for CS:S

**Comment by punkstarharis** [comment]
Kento, downloaded from github

**Comment by TandelK** [comment]
Did you use it once in the server even  ?  Or just without even starting RankMe in the server you tried installing this panel ?

**Comment by TandelK** [comment]
Check your Databases.cfg file and make sure you have "rankme" area and db name should be there and check the database what table has it created

**Comment by punkstarharis** [comment]
rankme was working fine without webpanel its showing ranks and topplayers but when i use webpanel server keep crashing

**Comment by TandelK** [comment]
Might be due to limits of SQL Server you are using . Also the user you use for connecting SQL to Webpanel does it has all access to that Database?

**Comment by punkstarharis** [comment]
yes full access to database and database have 2 tables auto created users, servers

**Comment by punkstarharis** [comment]
already rankme and database details in database.cfg im also using sourceban and its working fine without any issues

**Comment by TandelK** [comment]
i see they should already have rankme table which is not there. Do you see that databases.cfg rankme "" has the same database name as per the one you are connecting to webpanel ?

**Comment by punkstarharis** [comment]
yes everything is ok there

**Comment by TandelK** [comment]
PM me Steam : TandelK

**Comment by punkstarharis** [comment]
ADDED YOU - [A]zonic ' steelseries

**Comment by kennyLtv** [comment]
Did you get this resolved? Also, we don't edit anything on your server so it is unlikely that the web panel is causing your server to crash.

**Comment by punkstarharis** [comment]
i wanted to use it badly is there any complete tut availible? maybe i have did something wrong that's why its causing errors

**Comment by kennyLtv** [comment]
There is not a complete tutorial available I hope to in the next month or so release a new system that should make the whole web panel better. Usually, we see this error when there is an issue in the database configuration. Is the base table for your rankme install `rankme`?

**Comment by kennyLtv** [comment]
Ok so like I suspected. Those 2 tables (servers & users) are created by our web panel for the services it provides. The `rankme` table would be created by the server plugin. So if you haven't connected a rankme server to the database that is why you get that error. The plugin will generate the rankme table for us to read.

**Comment by punkstarharis** [comment]
already connected, im also using sourceban with same details and its working fine
![image](https://user-images.githubusercontent.com/28386395/41811623-889c5e62-772c-11e8-8e7f-0f1fbcac0391.png)

**Comment by punkstarharis** [comment]
already connected
![2018 06 23-19 14](https://user-images.githubusercontent.com/28386395/41811643-d80580f0-772c-11e8-9057-875f744be084.png)

**Comment by kennyLtv** [comment]
The game server should generate the rankme table structure. Does the game server plugin error or have you connected to the game server?

**Comment by kennyLtv** [comment]
Also, you may want to change your password if that is actually it.

**Comment by punkstarharis** [comment]
gameserver is keep crashing and in the logs its only show some geoip errors

**Comment by punkstarharis** [comment]
![41807542-8bc252e2-76e9-11e8-8b07-90ff17c1035a](https://user-images.githubusercontent.com/28386395/41811725-619871be-772e-11e8-9d9a-b2f7b3d18ed9.PNG)

**Comment by kennyLtv** [comment]
I'm not sure, you must have some sort of misconfiguration error on your game server side. We don't interact with the game server at all. Sadly there isn't a lot I can do to help you because our web panel can't make your server crash. I would suggest double checking your plugin install. Please let us know if you have any further issues with the web panel itself.

**Comment by punkstarharis** [comment]
Thanks for your time and help it was my database issue and now i have tried another database from different website and its working fine now thanks again and i will be waiting for new webpanel
