### ISSUE TITLE
README spelling/grammar

### ISSUE THREAD

**Issue by carterkelly9** [ToxicRevolution/CSGORankMeWeb#47]
The README should be tweaked to fix a few writing errors.

**Comment by kennyLtv** [comment]
I'm closing this as we will be updating the readme and wiki with the next release. That release hopefully will be tagged by the end of July. Also, you could always submit a PR if you believe you could do something better instead of just saying it needs fixed :(

**Comment by carterkelly9** [comment]
Sorry was attempting to do the PR but got sidetracked and then was away for a few days! Will have it done by today or tomorrow. :)
