### ISSUE TITLE
Ajax Error on leadboards.php

### ISSUE THREAD

**Issue by M-archand** [ToxicRevolution/CSGORankMeWeb#49]
Getting this error when attempting to go to the leaderboard page.

`DataTables warning: table id=LeaderBoardTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

I've never had issues with other variations of web panels for RankMe (3.0.3.Kento.27)

**Comment by kennyLtv** [comment]
Do you have a `rankme` table in your SQL database?

**Comment by M-archand** [comment]
Yes of course

**Comment by kennyLtv** [comment]
Are you able to provide a screenshot or something of the database and any error logs other than that? We normally have seen that error when someone renames the default RankMe table or they haven't run the server plugin to generate the table.

**Comment by M-archand** [comment]
Table is default rankme name, been using it for a while, has 10k+ records in it, and I've queried to it from other RankMe web panels before so I don't think that's the issue. I'll see what my browser dev console spits out later today.

**Comment by kennyLtv** [comment]
Did you happen to get the console output or did you resolve this on your own?

**Comment by M-archand** [comment]
Sorry, was away. I'm getting a 500 server error because of my `no-referrer-when-downgrade` policy.

Error looks something like this:

`Request URL: http://xyz.xyz/control/leaderboard/leaderboardGrab.php?*bunch of garbage*`
`Request Method: GET`
`Status Code: 500 Internal Server Error`
`Remote Address: xx.xx.xx.xx:xx`
`Referrer Policy: no-referrer-when-downgrade`

My site only uses http so i'm not sure why I'm getting this error, I don't know enough about apache to be honest, any suggestions?

**Comment by kennyLtv** [comment]
Sorry, I was traveling.

I'm fairly sure that the `no-referrer-when-downgrade` is not related to the 500 error. Do you have any errors in your PHP error_log? I think the errors in your UI is from the `leaderboardGrab.php` throwing the 500 error, we just need to know the error in your PHP error log to try and solve the problem.

**Comment by M-archand** [comment]
These are the errors that are thrown when going to that page in my log.

`PHP Notice:  Undefined variable: sql_details in /home/admin/web/...../control/leaderboard/leaderboardGrab.php on line 77, referer: http://..../leaderboards.php`

`PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /home/admin/web/..../control/leaderboard/ssp.class.php:423\nStack trace:\n#0 /home/admin/web/..../control/leaderboard/ssp.class.php(248): SSP::sql_exec(NULL, Array, 'SELECT `name`, ...')\n#1 /home/admin/web/..../control/leaderboard/leaderboardGrab.php(77): SSP::simple(Array, NULL, 'rankme', 'id', Array)\n#2 {main}\n  thrown in /home/admin/web/..../control/leaderboard/ssp.class.php on line 423, referer: http://..../leaderboards.php`

I first thought it might be an sql config error but I dont see $sql_details in the config so.. The install process wasn't writing to the config.php so I manually put the values in. Maybe I configured it wrong... what is $dbh supposed to look like?

Mine is `$dbh = new PDO("mysql:host=XX.XX.XX.XX ;dbname=my_dbname", 'my_dbuser', 'mypassword');`

**Comment by kennyLtv** [comment]
Yea it would appear we construct an array now in addition to the `$dbh`. Try adding this to your config with your database information and seeing if that fixes your issue. When we did that we didn't update the example config or complete the transition to the SQL class we are using it would appear. Likely as we are rewriting the system.

```
$sql_details = array(
			'user' => '',
			'pass' => '',
			'db' => '',
			'host' => ''
);
```

**Comment by kennyLtv** [comment]
I have updated the `example.config.php` to reflect this change now as well.

**Comment by M-archand** [comment]
This fixed it, thank you for the help man I appreciate it!
