### ISSUE TITLE
Unique characters not shown correctly

### ISSUE THREAD

**Issue by M-archand** [ToxicRevolution/CSGORankMeWeb#50]
This is basically a duplicate of #34 however my database is already using the utf8mb4 charset and they show correctly on my other RankMe lb.

Here's my old one vs this lb: 
![jiurnqo](https://user-images.githubusercontent.com/13469995/42658951-25a75048-85fd-11e8-830a-61e7f570df41.png)

**Comment by kennyLtv** [comment]
So at a quick glance, the Class we use for the Leaderboard SQL queries is [here](https://github.com/ToxicRevolution/CSGORankMeWeb/blob/master/control/leaderboard/ssp.class.php#L390). That specific line alters the connection to return a character set for UTF-8 encoding. Which should make the database return something the browser should render. We then have set in the metadata for the page the UTF-8 Data type so the browser knows what it is receiving. 

I'll have to double check a couple of things on our install but one of those is likely the reason you are still getting funny looking characters. I'll check our DB side and client side a little more and see if I can find a solution. If not I'll be sure that the rewrite does return the correct characters.

**Comment by kennyLtv** [comment]
Any chance you can send me a screenshot of them in the database? Our install is returning them correctly, specifically the ✪ as it is the most common one I know and could look for in our database.

**Comment by M-archand** [comment]
Hmm shit I just noticed they aren't showing correctly in my db, I remember converting the rankme table when I upgrade it a long time ago and the original must of been some shitty charset, so the special chars are all stored as garbage in my db. I'm guessing the RankMe page I'm using right now converts them when rendering on the page idk...
