### ISSUE TITLE
Profile buttons?

### ISSUE THREAD

**Issue by spacecow123** [ToxicRevolution/CSGORankMeWeb#7]
Is there any way to add a button next to each player like in this web interface?
http://ranking.1hp-gaming.com
I believe this is the code that they use:

[showplayer2.txt](https://github.com/ToxicRevolution/CSGORankMeWeb/files/876989/showplayer2.txt)

**Comment by spacecow123** [comment]
Here is their whole file

[rankme web 2016.zip](https://github.com/ToxicRevolution/CSGORankMeWeb/files/876990/rankme.web.2016.zip)

**Comment by APet74** [comment]
Let me go try and work one out real quick, hold tight!

**Comment by APet74** [comment]
Ok, Uploading solution, download again for working model!!!

**Comment by tibehrius** [comment]
I was expecting it too. Thank you very much!

**Comment by APet74** [comment]
Yes, let me know if you have any further issues.
