### ISSUE TITLE
Webrank write sqlite

### ISSUE THREAD

**Issue by szogi1910** [ToxicRevolution/CSGORankMeWeb#8]
I have a small problem with the web version
I uploaded to the web server - CSGORankMeWeb by ToxicRevolution 
After entering the data in the config.php file. Does not display me any results plugin saves rank on sqlite

https://pastebin.com/p4EqXTns

**Comment by kennyLtv** [comment]
Does it give you any errors?

**Comment by kennyLtv** [comment]
Also I would like to note that we do not currently officially support SQLite.

**Comment by szogi1910** [comment]
I do not have any error logs, but the sqlite script only works if the web script is not able to read data from it
