### ISSUE TITLE
Success reported after setup, but config.php is never created?

### ISSUE THREAD

**Issue by pabp** [ToxicRevolution/CSGORankMeWeb#9]
Hi,

As above, I've tried chmodding the install folder and files to 777 and tried setting up with a prepared mySQL account (as I was configuring it as root@localhost before, passwordless which I thought might be causing the problem). It reports success every time, but when I check the parent directory there's no config.php present.

**Comment by kennyLtv** [comment]
Can you give us some information about your server?

**Comment by pabp** [comment]
Sure.

PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
mySQL Server version: 5.5.55-0+deb8u1 (Debian)

I'm running a few other web apps (phpmyadmin, Sourcebans++, phpbb3) on it as well, all of them behave normally.

**Comment by kennyLtv** [comment]
Is the ownership of the files correct. I have tested it today on 3 different servers and have not been able to get it to fail.

**Comment by pabp** [comment]
I own all the files, chowning them to root doesn't appear to have any effect. I can see now it's properly executing the SQL queries but for some reason it fails to write the file. Could it possibly have something to do with how I've got fastCGI set up in lighttpd?

This error shows up a fair bit in /var/log/lighttpd/error.log. Is it relevant at all?
`2017-05-03 18:15:53: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html4/install/installMethods.php on line 47`

**Comment by kennyLtv** [comment]
short answer is yes that error is relevant. 

Can you edit that file on line 8 where it says this `$fileMain = fopen("../config.php", "w");` and change it to an absolute path instead of a relative path. So /var/www/html4/config.php i believe in your case.

**Comment by pabp** [comment]
Ok, figured it out, the top level directory's permissions were wrong and that was keeping it from writing. Whoops. Sorry for taking up your time.

**Comment by kennyLtv** [comment]
No worries glad you got it figured out
